### ISSUE TITLE
Logical spot issue

### ISSUE THREAD

**Issue by Oybekjon** [Guncharted/LPChat#1]
https://github.com/Guncharted/LPChat/blob/4c9818445b5e6a41c999da2dafee85f9e283e6a5/Client/lp-chat/src/app/chat/message-editor/message-editor.component.ts#L23

There is a problem with this method. If you call Send twice before completing the first one what will happen?

**Comment by Guncharted** [comment]
Thanks! This will be fixed after adding JWT support to client app.
